version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/var/lib/postgresql/15
      - ./volumes/backups:/backups
    ports:
      - "4432:5432"

  dbbackups:
    volumes:
      - ./volumes/backups:/backups

  django:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: prod
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
